Fix embedding of custom.js and custom.css
Bug 1: b64encode expects a byte stream and not a string. Without adjust
this we get the following exception:

```
Container startup complete.
[2020-05-14 15:12:29 +0000] [59] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
  File "/opt/marv/lib/python3.7/site-packages/aiohttp/worker.py", line 58, in run
    self.loop.run_until_complete(self._task)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/marv/lib/python3.7/site-packages/aiohttp/worker.py", line 71, in _run
    app = await self.wsgi()
  File "/opt/marv/lib/python3.7/site-packages/marv/cli.py", line 152, in app_factory
    application = marv.app.create_app(site, app_root=approot)
  File "/opt/marv/lib/python3.7/site-packages/marv/app/__init__.py", line 54, in create_app
    data = base64.b64encode(Path(site.config.marv.frontenddir, 'custom.js').read_text())
  File "/usr/lib/python3.7/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
```

Bug 2: The script tag has changed in the index.html but was not updated
in the __init__.py accordingly. Without adjust this we get the following
exception:

```
[2020-05-15 10:51:41 +0000] [127] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
  File "/opt/marv/lib/python3.7/site-packages/aiohttp/worker.py", line 58, in run
    self.loop.run_until_complete(self._task)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/marv/lib/python3.7/site-packages/aiohttp/worker.py", line 71, in _run
    app = await self.wsgi()
  File "/home/marv/code/marv/marv/cli.py", line 152, in app_factory
    application = marv.app.create_app(site, app_root=approot)
  File "/home/marv/code/marv/marv/app/__init__.py", line 65, in create_app
    assert '<script async src="main-built.js"></script>' in index_html
AssertionError
```

Bug 3: We have to convert the byte streams to strings. Otherwise we will
have something like this in the HTML code (notice the b'..')

```
data:text/css;base64,b'LyoKICAgIHJlbmRlcmpzb24gc3R'
```

Signed-off-by: Andre Schröder <andre.schroeder@tomtom.com>